id: A00BCB01B
title: 'CANTO XVII: Amṛtādhigama'
type: translation
source_metadata:
  languages:
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:47:04.334326
  last_modified_at: 2022-03-01 23:47:04.334333
